/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CategoriesEnum } from "./categoriesenum";
import { ModelOperation } from "./modeloperation";
import { Expose, Type } from "class-transformer";

export class AccountDetailsAndActionsIntegration extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ModelOperation })
    @Expose({ name: "available_model_operations" })
    @Type(() => ModelOperation)
    availableModelOperations?: ModelOperation[];

    @SpeakeasyMetadata()
    @Expose({ name: "categories" })
    categories: CategoriesEnum[];

    @SpeakeasyMetadata()
    @Expose({ name: "color" })
    color: string;

    @SpeakeasyMetadata()
    @Expose({ name: "image" })
    image?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "passthrough_available" })
    passthroughAvailable: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "slug" })
    slug: string;

    @SpeakeasyMetadata()
    @Expose({ name: "square_image" })
    squareImage?: string;
}
