/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AccountIntegration } from "./accountintegration";
import { ModelOperation } from "./modeloperation";
import { Expose, Type } from "class-transformer";

/**
 * # The AvailableActions Object
 *
 * @remarks
 * ### Description
 * The `Activity` object is used to see all available model/operation combinations for an integration.
 *
 * ### Usage Example
 * Fetch all the actions available for the `Zenefits` integration.
 */
export class AvailableActions extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ModelOperation })
    @Expose({ name: "available_model_operations" })
    @Type(() => ModelOperation)
    availableModelOperations?: ModelOperation[];

    @SpeakeasyMetadata()
    @Expose({ name: "integration" })
    @Type(() => AccountIntegration)
    integration: AccountIntegration;

    @SpeakeasyMetadata()
    @Expose({ name: "passthrough_available" })
    passthroughAvailable: boolean;
}
