/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * * `hris` - hris
 *
 * @remarks
 * * `ats` - ats
 * * `accounting` - accounting
 * * `ticketing` - ticketing
 * * `crm` - crm
 * * `mktg` - mktg
 * * `filestorage` - filestorage
 */
export enum CategoriesEnum {
    Hris = "hris",
    Ats = "ats",
    Accounting = "accounting",
    Ticketing = "ticketing",
    Crm = "crm",
    Mktg = "mktg",
    Filestorage = "filestorage",
}
