/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * * `BOOLEAN` - BOOLEAN
 *
 * @remarks
 * * `DATE` - DATE
 * * `DATE_TIME` - DATE_TIME
 * * `INTEGER` - INTEGER
 * * `FLOAT` - FLOAT
 * * `STRING` - STRING
 * * `LIST_OF_STRINGS` - LIST_OF_STRINGS
 */
export enum ConditionTypeEnum {
    Boolean = "BOOLEAN",
    Date = "DATE",
    DateTime = "DATE_TIME",
    Integer = "INTEGER",
    Float = "FLOAT",
    String = "STRING",
    ListOfStrings = "LIST_OF_STRINGS",
}
