/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class DebugModelLogSummary extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "method" })
    method: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status_code" })
    statusCode: number;

    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}
