/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RemoteData } from "./remotedata";
import { Expose, Transform, Type } from "class-transformer";

/**
 * # The Deduction Object
 *
 * @remarks
 * ### Description
 * The `Deduction` object is used to represent an array of the wages withheld from total earnings for the purpose of paying taxes.
 *
 * ### Usage Example
 * Fetch from the `LIST Deductions` endpoint and filter by `ID` to show all deductions.
 */
export class Deduction extends SpeakeasyBase {
    /**
     * The amount of money that is withheld on behalf of an employee by the company.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "company_deduction" })
    companyDeduction?: number;

    /**
     * The amount of money that is withheld from an employee's gross pay by the employee.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "employee_deduction" })
    employeeDeduction?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "employee_payroll_run" })
    employeePayrollRun?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "field_mappings" })
    fieldMappings?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * This is the datetime that this object was last updated by Merge
     */
    @SpeakeasyMetadata()
    @Expose({ name: "modified_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    modifiedAt?: Date;

    /**
     * The deduction's name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata({ elemType: RemoteData })
    @Expose({ name: "remote_data" })
    @Type(() => RemoteData)
    remoteData?: RemoteData[];

    /**
     * The third-party API ID of the matching object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remote_id" })
    remoteId?: string;

    /**
     * Indicates whether or not this object has been deleted by third party webhooks.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remote_was_deleted" })
    remoteWasDeleted?: boolean;
}
