/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EmployeeRequest } from "./employeerequest";
import { Expose, Type } from "class-transformer";

export class EmployeeEndpointRequest extends SpeakeasyBase {
    /**
     * # The Employee Object
     *
     * @remarks
     * ### Description
     * The `Employee` object is used to represent any person who has been employed by a company.
     *
     * ### Usage Example
     * Fetch from the `LIST Employee` endpoint and filter by `ID` to show all employees.
     */
    @SpeakeasyMetadata({ data: "form, name=model;json=true, multipart_form, name=model;json=true" })
    @Expose({ name: "model" })
    @Type(() => EmployeeRequest)
    model: EmployeeRequest;
}
