/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * * `READ` - READ
 *
 * @remarks
 * * `WRITE` - WRITE
 */
export enum EnabledActionsEnum {
    Read = "READ",
    Write = "WRITE",
}
