/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CategoriesEnum } from "./categoriesenum";
import { CommonModelScopesBodyRequest } from "./commonmodelscopesbodyrequest";
import { Expose, Type } from "class-transformer";

export class EndUserDetailsRequest extends SpeakeasyBase {
    /**
     * The integration categories to show in Merge Link.
     */
    @SpeakeasyMetadata({ data: "form, name=categories, multipart_form, name=categories" })
    @Expose({ name: "categories" })
    categories: CategoriesEnum[];

    /**
     * An array of objects to specify the models and fields that will be disabled for a given Linked Account. Each object uses model_id, enabled_actions, and disabled_fields to specify the model, method, and fields that are scoped for a given Linked Account.
     */
    @SpeakeasyMetadata({
        data: "form, name=common_models;json=true, multipart_form, name=common_models;json=true",
        elemType: CommonModelScopesBodyRequest,
    })
    @Expose({ name: "common_models" })
    @Type(() => CommonModelScopesBodyRequest)
    commonModels?: CommonModelScopesBodyRequest[];

    /**
     * Your end user's email address. This is purely for identification purposes - setting this value will not cause any emails to be sent.
     */
    @SpeakeasyMetadata({
        data: "form, name=end_user_email_address, multipart_form, name=end_user_email_address",
    })
    @Expose({ name: "end_user_email_address" })
    endUserEmailAddress: string;

    /**
     * Your end user's organization.
     */
    @SpeakeasyMetadata({
        data: "form, name=end_user_organization_name, multipart_form, name=end_user_organization_name",
    })
    @Expose({ name: "end_user_organization_name" })
    endUserOrganizationName: string;

    /**
     * This unique identifier typically represents the ID for your end user in your product's database. This value must be distinct from other Linked Accounts' unique identifiers.
     */
    @SpeakeasyMetadata({
        data: "form, name=end_user_origin_id, multipart_form, name=end_user_origin_id",
    })
    @Expose({ name: "end_user_origin_id" })
    endUserOriginId: string;

    /**
     * The slug of a specific pre-selected integration for this linking flow token. For examples of slugs, see https://www.merge.dev/docs/basics/integration-metadata/.
     */
    @SpeakeasyMetadata({ data: "form, name=integration, multipart_form, name=integration" })
    @Expose({ name: "integration" })
    integration?: string;

    /**
     * An integer number of minutes between [30, 720 or 10080 if for a Magic Link URL] for how long this token is valid. Defaults to 30.
     */
    @SpeakeasyMetadata({
        data: "form, name=link_expiry_mins, multipart_form, name=link_expiry_mins",
    })
    @Expose({ name: "link_expiry_mins" })
    linkExpiryMins?: number;

    /**
     * Whether to generate a Magic Link URL. Defaults to false. For more information on Magic Link, see https://merge.dev/blog/integrations-fast-say-hello-to-magic-link.
     */
    @SpeakeasyMetadata({
        data: "form, name=should_create_magic_link_url, multipart_form, name=should_create_magic_link_url",
    })
    @Expose({ name: "should_create_magic_link_url" })
    shouldCreateMagicLinkUrl?: boolean;
}
