/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * * `GENERAL_CUSTOMER_REQUEST` - GENERAL_CUSTOMER_REQUEST
 *
 * @remarks
 * * `GDPR` - GDPR
 * * `OTHER` - OTHER
 */
export enum IgnoreCommonModelRequestReason {
    GeneralCustomerRequest = "GENERAL_CUSTOMER_REQUEST",
    Gdpr = "GDPR",
    Other = "OTHER",
}

export class IgnoreCommonModelRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "form, name=message, multipart_form, name=message" })
    @Expose({ name: "message" })
    message?: string;

    @SpeakeasyMetadata({ data: "form, name=reason, multipart_form, name=reason" })
    @Expose({ name: "reason" })
    reason: IgnoreCommonModelRequestReason;
}
