/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class IgnoreCommonModelRequest1 extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "form, name=message, multipart_form, name=message" })
    message?: string;

    @SpeakeasyMetadata({ data: "form, name=reason, multipart_form, name=reason" })
    reason: any;
}
