/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class LinkedAccountConditionRequest extends SpeakeasyBase {
    /**
     * The ID indicating which condition schema to use for a specific condition.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "condition_schema_id" })
    conditionSchemaId: string;

    /**
     * The operator for a specific condition.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "operator" })
    operator: string;

    /**
     * The value for a specific condition.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value: any;
}
