/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class LinkedAccountStatus extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "can_make_request" })
    canMakeRequest: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "linked_account_status" })
    linkedAccountStatus: string;
}
