/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LinkedAccountCondition } from "./linkedaccountcondition";
import { Expose, Type } from "class-transformer";

export class LinkedAccountSelectiveSyncConfiguration extends SpeakeasyBase {
    /**
     * The conditions belonging to a selective sync.
     */
    @SpeakeasyMetadata({ elemType: LinkedAccountCondition })
    @Expose({ name: "linked_account_conditions" })
    @Type(() => LinkedAccountCondition)
    linkedAccountConditions?: LinkedAccountCondition[];
}
