/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class OperatorSchema extends SpeakeasyBase {
    /**
     * Whether the operator can be repeated multiple times.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "is_unique" })
    isUnique?: boolean;

    /**
     * The operator for which an operator schema is defined.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "operator" })
    operator?: string;
}
