/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AccountDetailsAndActions } from "./accountdetailsandactions";
import { Expose, Type } from "class-transformer";

export class PaginatedAccountDetailsAndActionsList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: AccountDetailsAndActions })
    @Expose({ name: "results" })
    @Type(() => AccountDetailsAndActions)
    results?: AccountDetailsAndActions[];
}
