/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConditionSchema } from "./conditionschema";
import { Expose, Type } from "class-transformer";

export class PaginatedConditionSchemaList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: ConditionSchema })
    @Expose({ name: "results" })
    @Type(() => ConditionSchema)
    results?: ConditionSchema[];
}
