/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TimeOff } from "./timeoff";
import { Expose, Type } from "class-transformer";

export class PaginatedTimeOffList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: TimeOff })
    @Expose({ name: "results" })
    @Type(() => TimeOff)
    results?: TimeOff[];
}
