/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BankInfo } from "./bankinfo";
import { Expose, Type } from "class-transformer";

export class PaginatedBankInfoList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: BankInfo })
    @Expose({ name: "results" })
    @Type(() => BankInfo)
    results?: BankInfo[];
}
