/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SyncStatus } from "./syncstatus";
import { Expose, Type } from "class-transformer";

export class PaginatedSyncStatusList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: SyncStatus })
    @Expose({ name: "results" })
    @Type(() => SyncStatus)
    results?: SyncStatus[];
}
