/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PayGroup } from "./paygroup";
import { Expose, Type } from "class-transformer";

export class PaginatedPayGroupList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: PayGroup })
    @Expose({ name: "results" })
    @Type(() => PayGroup)
    results?: PayGroup[];
}
