/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EmployeePayrollRun } from "./employeepayrollrun";
import { Expose, Type } from "class-transformer";

export class PaginatedEmployeePayrollRunList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: EmployeePayrollRun })
    @Expose({ name: "results" })
    @Type(() => EmployeePayrollRun)
    results?: EmployeePayrollRun[];
}
