/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PayrollRun } from "./payrollrun";
import { Expose, Type } from "class-transformer";

export class PaginatedPayrollRunList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: PayrollRun })
    @Expose({ name: "results" })
    @Type(() => PayrollRun)
    results?: PayrollRun[];
}
