/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * # The RemoteKey Object
 *
 * @remarks
 * ### Description
 * The `RemoteKey` object is used to represent a request for a new remote key.
 *
 * ### Usage Example
 * Post a `GenerateRemoteKey` to receive a new `RemoteKey`.
 */
export class RemoteKey extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}
