/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * * `IN_NEXT_SYNC` - IN_NEXT_SYNC
 *
 * @remarks
 * * `IN_LAST_SYNC` - IN_LAST_SYNC
 */
export enum SelectiveSyncConfigurationsUsageEnum {
    InNextSync = "IN_NEXT_SYNC",
    InLastSync = "IN_LAST_SYNC",
}
