/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RemoteData } from "./remotedata";
import { Expose, Transform, Type } from "class-transformer";

/**
 * The policy type of this time off balance.
 *
 * @remarks
 *
 * * `VACATION` - VACATION
 * * `SICK` - SICK
 * * `PERSONAL` - PERSONAL
 * * `JURY_DUTY` - JURY_DUTY
 * * `VOLUNTEER` - VOLUNTEER
 * * `BEREAVEMENT` - BEREAVEMENT
 */
export enum PolicyType {
    Vacation = "VACATION",
    Sick = "SICK",
    Personal = "PERSONAL",
    JuryDuty = "JURY_DUTY",
    Volunteer = "VOLUNTEER",
    Bereavement = "BEREAVEMENT",
}

/**
 * # The TimeOffBalance Object
 *
 * @remarks
 * ### Description
 * The `TimeOffBalance` object is used to represent current balances for an employee's Time Off plan.
 *
 * ### Usage Example
 * Fetch from the `LIST TimeOffBalances` endpoint and filter by `ID` to show all time off balances.
 */
export class TimeOffBalance extends SpeakeasyBase {
    /**
     * The current remaining PTO balance, always measured in terms of hours.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "balance" })
    balance?: number;

    /**
     * The employee the balance belongs to.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "employee" })
    employee?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "field_mappings" })
    fieldMappings?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * This is the datetime that this object was last updated by Merge
     */
    @SpeakeasyMetadata()
    @Expose({ name: "modified_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    modifiedAt?: Date;

    /**
     * The policy type of this time off balance.
     *
     * @remarks
     *
     * * `VACATION` - VACATION
     * * `SICK` - SICK
     * * `PERSONAL` - PERSONAL
     * * `JURY_DUTY` - JURY_DUTY
     * * `VOLUNTEER` - VOLUNTEER
     * * `BEREAVEMENT` - BEREAVEMENT
     */
    @SpeakeasyMetadata()
    @Expose({ name: "policy_type" })
    policyType?: PolicyType;

    @SpeakeasyMetadata({ elemType: RemoteData })
    @Expose({ name: "remote_data" })
    @Type(() => RemoteData)
    remoteData?: RemoteData[];

    /**
     * The third-party API ID of the matching object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remote_id" })
    remoteId?: string;

    /**
     * Indicates whether or not this object has been deleted by third party webhooks.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remote_was_deleted" })
    remoteWasDeleted?: boolean;

    /**
     * The amount of PTO used in terms of hours.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "used" })
    used?: number;
}
