/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class WebhookReceiverRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "form, name=event, multipart_form, name=event" })
    @Expose({ name: "event" })
    event: string;

    @SpeakeasyMetadata({ data: "form, name=is_active, multipart_form, name=is_active" })
    @Expose({ name: "is_active" })
    isActive: boolean;

    @SpeakeasyMetadata({ data: "form, name=key, multipart_form, name=key" })
    @Expose({ name: "key" })
    key?: string;
}
