/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class EmployeesCreateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    employeeEndpointRequest: shared.EmployeeEndpointRequest;

    /**
     * Token identifying the end user.
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Account-Token" })
    xAccountToken: string;

    /**
     * Whether to include debug fields (such as log file links) in the response.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=is_debug_mode" })
    isDebugMode?: boolean;

    /**
     * Whether or not third-party updates should be run asynchronously.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=run_async" })
    runAsync?: boolean;
}

export class EmployeesCreateResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    employeeResponse?: shared.EmployeeResponse;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
