/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

/**
 * Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
 */
export enum EmploymentsListExpand {
    Employee = "employee",
    EmployeePayGroup = "employee,pay_group",
    PayGroup = "pay_group",
}

/**
 * Overrides the default ordering for this endpoint.
 */
export enum EmploymentsListOrderBy {
    MinusEffectiveDate = "-effective_date",
    EffectiveDate = "effective_date",
}

/**
 * Deprecated. Use show_enum_origins.
 */
export enum EmploymentsListRemoteFields {
    EmploymentType = "employment_type",
    EmploymentTypeFlsaStatus = "employment_type,flsa_status",
    EmploymentTypeFlsaStatusPayFrequency = "employment_type,flsa_status,pay_frequency",
    EmploymentTypeFlsaStatusPayFrequencyPayPeriod = "employment_type,flsa_status,pay_frequency,pay_period",
    EmploymentTypeFlsaStatusPayPeriod = "employment_type,flsa_status,pay_period",
    EmploymentTypePayFrequency = "employment_type,pay_frequency",
    EmploymentTypePayFrequencyPayPeriod = "employment_type,pay_frequency,pay_period",
    EmploymentTypePayPeriod = "employment_type,pay_period",
    FlsaStatus = "flsa_status",
    FlsaStatusPayFrequency = "flsa_status,pay_frequency",
    FlsaStatusPayFrequencyPayPeriod = "flsa_status,pay_frequency,pay_period",
    FlsaStatusPayPeriod = "flsa_status,pay_period",
    PayFrequency = "pay_frequency",
    PayFrequencyPayPeriod = "pay_frequency,pay_period",
    PayPeriod = "pay_period",
}

/**
 * Which fields should be returned in non-normalized form.
 */
export enum EmploymentsListShowEnumOrigins {
    EmploymentType = "employment_type",
    EmploymentTypeFlsaStatus = "employment_type,flsa_status",
    EmploymentTypeFlsaStatusPayFrequency = "employment_type,flsa_status,pay_frequency",
    EmploymentTypeFlsaStatusPayFrequencyPayPeriod = "employment_type,flsa_status,pay_frequency,pay_period",
    EmploymentTypeFlsaStatusPayPeriod = "employment_type,flsa_status,pay_period",
    EmploymentTypePayFrequency = "employment_type,pay_frequency",
    EmploymentTypePayFrequencyPayPeriod = "employment_type,pay_frequency,pay_period",
    EmploymentTypePayPeriod = "employment_type,pay_period",
    FlsaStatus = "flsa_status",
    FlsaStatusPayFrequency = "flsa_status,pay_frequency",
    FlsaStatusPayFrequencyPayPeriod = "flsa_status,pay_frequency,pay_period",
    FlsaStatusPayPeriod = "flsa_status,pay_period",
    PayFrequency = "pay_frequency",
    PayFrequencyPayPeriod = "pay_frequency,pay_period",
    PayPeriod = "pay_period",
}

export class EmploymentsListRequest extends SpeakeasyBase {
    /**
     * Token identifying the end user.
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Account-Token" })
    xAccountToken: string;

    /**
     * If provided, will only return objects created after this datetime.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created_after" })
    createdAfter?: Date;

    /**
     * If provided, will only return objects created before this datetime.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created_before" })
    createdBefore?: Date;

    /**
     * The pagination cursor value.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=cursor" })
    cursor?: string;

    /**
     * If provided, will only return employments for this employee.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=employee_id" })
    employeeId?: string;

    /**
     * Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=expand" })
    expand?: EmploymentsListExpand;

    /**
     * Whether to include data that was marked as deleted by third party webhooks.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=include_deleted_data" })
    includeDeletedData?: boolean;

    /**
     * Whether to include the original data Merge fetched from the third-party to produce these models.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=include_remote_data" })
    includeRemoteData?: boolean;

    /**
     * If provided, only objects synced by Merge after this date time will be returned.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=modified_after" })
    modifiedAfter?: Date;

    /**
     * If provided, only objects synced by Merge before this date time will be returned.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=modified_before" })
    modifiedBefore?: Date;

    /**
     * Overrides the default ordering for this endpoint.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=order_by" })
    orderBy?: EmploymentsListOrderBy;

    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page_size" })
    pageSize?: number;

    /**
     * Deprecated. Use show_enum_origins.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=remote_fields" })
    remoteFields?: EmploymentsListRemoteFields;

    /**
     * The API provider's ID for the given object.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=remote_id" })
    remoteId?: string;

    /**
     * Which fields should be returned in non-normalized form.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=show_enum_origins" })
    showEnumOrigins?: EmploymentsListShowEnumOrigins;
}

export class EmploymentsListResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    paginatedEmploymentList?: shared.PaginatedEmploymentList;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
